# Generated by Django 2.0.7 on 2018-07-26 20:21

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(blank=True, upload_to='blog_image')),
                ('likes_count', models.IntegerField(blank=True, default=0)),
                ('comments', jsonfield.fields.JSONField(blank=True, default=None)),
                ('flags', jsonfield.fields.JSONField(blank=True, default=None)),
                ('tags', jsonfield.fields.JSONField(default=None)),
                ('tinymce', models.TextField(max_length=4000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BlogDescriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('topic_image', models.ImageField(blank=True, upload_to='topic_image')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ListTopicsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(default='ml001', max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('username', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'List topics models',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('user_Id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic')),
                ('followers', jsonfield.fields.JSONField(blank=True, default=None)),
                ('followers_count', models.IntegerField(blank=True, default=0)),
                ('about_me', models.TextField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('validate', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='blogdescriptionmodel',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hacks_to_code.ListTopicsModels'),
        ),
        migrations.AddField(
            model_name='blogdescriptionmodel',
            name='user_Id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='hacks_to_code.UserProfile'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hacks_to_code.BlogDescriptionModel'),
        ),
    ]
