# Generated by Django 2.0.7 on 2018-07-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
