# Generated by Django 2.0.5 on 2018-07-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdescriptionmodel',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='blogdescriptionmodel',
            name='topic_image',
            field=models.ImageField(blank=True, upload_to='topic_image'),
        ),
    ]
