# Generated by Django 2.0.5 on 2018-07-08 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0002_auto_20180708_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdescriptionmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='blogdescriptionmodel',
            name='topic_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
