# Generated by Django 2.0.7 on 2018-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0002_auto_20180727_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdescriptionmodel',
            name='name',
            field=models.CharField(default='Blog Name not Given', max_length=255),
        ),
    ]
