# Generated by Django 2.0.7 on 2018-07-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0003_auto_20180729_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tinymce',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='blogdescriptionmodel',
            name='description',
            field=models.TextField(default='No description Given'),
        ),
    ]
