# Generated by Django 2.0.5 on 2018-07-18 04:26

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0003_auto_20180708_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(blank=True, upload_to='blog_image')),
                ('likes_count', models.IntegerField(blank=True, default=0)),
                ('comments', jsonfield.fields.JSONField(default=None)),
                ('flags', jsonfield.fields.JSONField(default=None)),
                ('tags', jsonfield.fields.JSONField(default=None)),
                ('tinymce', models.TextField(max_length=4000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('user_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic')),
                ('followers', jsonfield.fields.JSONField(default=None)),
                ('followers_count', models.IntegerField(blank=True, default=0)),
                ('about_me', models.TextField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('validate', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.RemoveField(
            model_name='blogdescriptionmodel',
            name='user_detail',
        ),
        migrations.RemoveField(
            model_name='blogdescriptionmodel',
            name='username',
        ),
        migrations.AddField(
            model_name='blog',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hacks_to_code.BlogDescriptionModel'),
        ),
        migrations.AddField(
            model_name='blogdescriptionmodel',
            name='user_Id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='hacks_to_code.UserProfile'),
        ),
    ]
