# Generated by Django 2.0.7 on 2018-07-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0004_auto_20180729_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdescriptionmodel',
            old_name='name',
            new_name='blog_name',
        ),
        migrations.RenameField(
            model_name='listtopicsmodels',
            old_name='name',
            new_name='topic_name',
        ),
    ]
