# Generated by Django 2.0.5 on 2018-07-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0004_auto_20180718_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtopicsmodels',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
