# Generated by Django 2.0.5 on 2018-07-18 17:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0005_auto_20180718_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=jsonfield.fields.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='blog',
            name='flags',
            field=jsonfield.fields.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=jsonfield.fields.JSONField(blank=True, default=None),
        ),
    ]
