# Generated by Django 2.0.7 on 2018-07-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0005_auto_20180729_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdescriptionmodel',
            old_name='description',
            new_name='blog_description',
        ),
        migrations.RenameField(
            model_name='blogdescriptionmodel',
            old_name='is_published',
            new_name='blog_is_published',
        ),
        migrations.RenameField(
            model_name='listtopicsmodels',
            old_name='description',
            new_name='topic_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_published',
        ),
    ]
