# Generated by Django 2.0.7 on 2018-07-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0006_auto_20180729_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdescriptionmodel',
            old_name='blog_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blogdescriptionmodel',
            old_name='blog_is_published',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='blogdescriptionmodel',
            old_name='blog_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='listtopicsmodels',
            old_name='topic_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='listtopicsmodels',
            old_name='topic_name',
            new_name='name',
        ),
    ]
