# Generated by Django 2.0.7 on 2018-07-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0008_auto_20180730_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='static/home/img/back.jpg', upload_to='blog_image'),
        ),
        migrations.AlterField(
            model_name='blogdescriptionmodel',
            name='topic_image',
            field=models.ImageField(default='static/home/img/htc_icon.png', upload_to='topic_image'),
        ),
    ]
