# Generated by Django 2.0.7 on 2018-07-31 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0009_auto_20180730_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user_Id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='hacks_to_code.UserProfile'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='backup/back.jpg', upload_to='blog_image'),
        ),
        migrations.AlterField(
            model_name='blogdescriptionmodel',
            name='topic_image',
            field=models.ImageField(default='backup/htc_icon.png', upload_to='topic_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='backup/meicon.png', upload_to='profile_pic'),
        ),
    ]
