# Generated by Django 2.0.7 on 2018-08-04 19:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0010_auto_20180731_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tinymce',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
