# Generated by Django 2.0.7 on 2018-08-04 20:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0011_auto_20180804_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tinymce',
            field=tinymce.models.HTMLField(verbose_name='tinymce'),
        ),
    ]
