# Generated by Django 2.1 on 2018-08-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks_to_code', '0015_auto_20180804_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdescriptionmodel',
            name='name',
            field=models.CharField(default='Blog Name not Given', max_length=255, unique=True),
        ),
    ]
