# Generated by Django 2.0.5 on 2018-07-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_part', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogDescriptionModel',
        ),
        migrations.DeleteModel(
            name='ListTopicsModels',
        ),
    ]
